name = "vfcvt.f.x.v"
format = "vd,vs2,vm"

supported_zve = ["Zve32f", "Zve64f", "Zve64d"]

[tests]
sew32 = [
    [0xffffffff],
    [0xfffffffe],
    [0x2],
]

sew64 = [
    ["0xffffffffffffffff"],
    ["0xfffffffffffffffe"],
    ["0x2"]
]