name = "vfmin.vf"
format = "vd,vs2,fs1,vm"

supported_zve = ["Zve32f", "Zve64f", "Zve64d"]

[tests]
fsew32 = [
    [2.5,           1.0],
    [-1235.1,       1.1],
    [3.14159265,    0.00000001]
]
fsew64 = [
    [2.5,           1.0],
    [-1235.1,       1.1],
    [3.14159265,    0.00000001]
]
