name = "vmandn.mm"
format = "vd,vs2,vs1"

supported_zve = ["Zve32x", "Zve32f", "Zve64x", "Zve64f", "Zve64d"]

[tests]
base = [
    [0xff, 0x0f],
    [0x00, 0x0f],
    [0x0f, 0xf0],
    [0xf0, 0x0f],
    [0xf0, 0xf0]
]