name = "vmv.v.v"
format = "vd,vs1"

supported_zve = ["Zve32x", "Zve32f", "Zve64x", "Zve64f", "Zve64d"]

[tests]
base = []
sew8 = [[0xd6]]
sew16 = [[0xffd6]]
sew32 = [[0xffffffd6]]
sew64 = [["0xffffffffffffffd6"]]
