name = "vsetvl"
format = "vsetvl"

supported_zve = ["Zve32x", "Zve32f", "Zve64x", "Zve64f", "Zve64d"]

[tests]
base = [
    [0x0, 0x0, 0x0],
    [0x0, 0x0, 0xd],
    [0x1, 0x1, 0x2],
    [0x3, 0x3, 0xf]
]