name = "vsse64.v"
format = "vs3,(rs1),rs2,vm"

supported_zve = ["Zve32x", "Zve32f", "Zve64x", "Zve64f", "Zve64d"]

[tests]
base = [
    [0x0],
    [0x1],
    [0x2],
    [0xf]
]
sew64 = [
    ["0x7fffffffffffffff"],
    ["0xfffffffffffffff8"],
    ["0xffffffffffffffff"]
]